---
title: "First Knit"
author: "Kaylie Brehm"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I went to High School at Antelope Valley Learning Academy under the organization Learn4Life. I graduated a year and a half early with online coursework. I love math because of its definitive nature, unlike English which is up to interpretation. The subject I did best in was Algebra II. Interestingly, I dislike Statistics.
     
## Your computer and your and its capability?  
For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have a Windows desktop, an HP Omen. My computer was purchased primarily for gaming, but I consider myself to be moderate in terms of computer knowledge, probably a 6. I live in Tehachapi so the wind can conflict with internet connection, but it shouldn't be too much of an issue.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   My name is Kaylie Brehm and I am okay with everyone using that.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   I want to do something within the medical field, whether that be a doctor, nurse, or first responder. Right now I am striving for my Bachelors in Science of Nursing but I will most likely go further with my education, as I love school. My greatest interest in subject would most likely be anatomy or kinesiology.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I stopped at Ensenada, Mexico during on a cruise when I was a kid but have not traveled much besides that. However, last year, I had multiple family members move out of state. This allowed me to visit them and go on a plane for the first time. I have never been in the military, but if I did go, I would want to be in a medical environment. 
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I took Math 115 because it is a requirement by my counselor. In order for me to take Chemistry next semester, I need to pass. But I am going to try and get an A regardless. In all honesty, I do not like statistics. I would have much rather taken any form of Algebra or Trig. 
   
 






  




